/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import EDD.HashTable;
import EDD.List;
import EDD.Nodo;
import EDD.Resumenes;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.PrintWriter;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Tomas
 */
public class Ventana extends javax.swing.JFrame {

    DefaultListModel model =new DefaultListModel();

    DefaultListModel modelo = new DefaultListModel();
    
    /**
     * Creates new form Ventana_1
     */
    public Ventana() {
        initComponents();        
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        TitulosOrdenados.setModel(model);
        AutoresOrdenados.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pannel = new javax.swing.JPanel();
        LeerTXT = new javax.swing.JButton();
        Cerrar = new javax.swing.JButton();
        Analizar = new javax.swing.JButton();
        BuscarAutor = new javax.swing.JButton();
        BuscarClave = new javax.swing.JButton();
        Parent = new javax.swing.JPanel();
        main = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Analize = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TitulosOrdenados = new javax.swing.JList<>();
        Buscar_Datos = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        Search_Author = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        ComboBox = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        AutoresOrdenados = new javax.swing.JList<>();
        Buscar_Datos1 = new javax.swing.JButton();
        Search_Key = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        Busqueda_Datos = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        datosResumen = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pannel.setBackground(new java.awt.Color(0, 0, 0));
        Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LeerTXT.setFont(new java.awt.Font("Swis721 BT", 0, 12)); // NOI18N
        LeerTXT.setText("LEER TXT");
        LeerTXT.setPreferredSize(new java.awt.Dimension(80, 25));
        LeerTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeerTXTActionPerformed(evt);
            }
        });
        Pannel.add(LeerTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 130, -1));

        Cerrar.setFont(new java.awt.Font("Swis721 BT", 0, 12)); // NOI18N
        Cerrar.setText("CERRAR");
        Cerrar.setMaximumSize(new java.awt.Dimension(84, 22));
        Cerrar.setMinimumSize(new java.awt.Dimension(84, 22));
        Cerrar.setPreferredSize(new java.awt.Dimension(80, 25));
        Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarActionPerformed(evt);
            }
        });
        Pannel.add(Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 130, -1));

        Analizar.setFont(new java.awt.Font("Swis721 BT", 0, 12)); // NOI18N
        Analizar.setText("ANALIZAR");
        Analizar.setPreferredSize(new java.awt.Dimension(80, 25));
        Analizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalizarActionPerformed(evt);
            }
        });
        Pannel.add(Analizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 130, -1));

        BuscarAutor.setFont(new java.awt.Font("Swis721 BT", 0, 12)); // NOI18N
        BuscarAutor.setText("BUSCAR AUTOR");
        BuscarAutor.setPreferredSize(new java.awt.Dimension(80, 25));
        BuscarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarAutorActionPerformed(evt);
            }
        });
        Pannel.add(BuscarAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 130, -1));

        BuscarClave.setFont(new java.awt.Font("Swis721 BT", 0, 12)); // NOI18N
        BuscarClave.setText("BUSCAR CLAVES");
        BuscarClave.setPreferredSize(new java.awt.Dimension(80, 25));
        BuscarClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarClaveActionPerformed(evt);
            }
        });
        Pannel.add(BuscarClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 130, -1));

        getContentPane().add(Pannel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 540));

        Parent.setBackground(new java.awt.Color(255, 255, 255));
        Parent.setLayout(new java.awt.CardLayout());

        main.setBackground(new java.awt.Color(255, 255, 255));
        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Swis721 Cn BT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("MetroMendeley");
        main.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Swis721 BT", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("una gran variedad de resúmenes acerca de artículos científicos.");
        main.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Swis721 BT", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("terminará su ejecución.");
        main.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        jLabel4.setFont(new java.awt.Font("Swis721 BT", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Bienvenido a la base de Datos de MetroMendeley, aquí encontrarás");
        main.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Swis721 BT", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Con el botón de Leer TXT podrás cargar resúmenes a la base de datos");
        main.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Swis721 BT", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("En la sección de Analizar resúmenes podrás observar la lista de ");
        main.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Swis721 BT", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("resúmenes en la base de datos, y serás capaz de seleccionar uno");
        main.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("Swis721 BT", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("para poder analizarlo.");
        main.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Swis721 BT", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("En la sección de búsqueda por autor, podrás buscar todos los ");
        main.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel10.setFont(new java.awt.Font("Swis721 BT", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("resúmenes creados por el autor que usted introduzca, y será capaz");
        main.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel11.setFont(new java.awt.Font("Swis721 BT", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("de ver los detalles de ese resúmen.");
        main.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel12.setFont(new java.awt.Font("Swis721 BT", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("En la sección de búsqueda por palabra clave, podrás buscar todos los");
        main.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jLabel13.setFont(new java.awt.Font("Swis721 BT", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("resúmenes que contengan la palabra clave que usted introduzca");
        main.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jLabel14.setFont(new java.awt.Font("Swis721 BT", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("y será capaz de ver los detalles de ese resúmen.");
        main.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jLabel15.setFont(new java.awt.Font("Swis721 BT", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Finalmente en el botón de salir del sistema, se guardarán todos los");
        main.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jLabel16.setFont(new java.awt.Font("Swis721 BT", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("datos que se hayan introducido a la base de datos, y el programa");
        main.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        Parent.add(main, "card2");

        Analize.setBackground(new java.awt.Color(255, 255, 255));
        Analize.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Swis721 Cn BT", 1, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Analizar Resúmenes");
        Analize.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        TitulosOrdenados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TitulosOrdenados.setToolTipText("");
        jScrollPane2.setViewportView(TitulosOrdenados);

        Analize.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 510, 350));

        Buscar_Datos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Buscar_Datos.setText("BUSCAR");
        Buscar_Datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar_DatosActionPerformed(evt);
            }
        });
        Analize.add(Buscar_Datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 220, 40));

        jLabel20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Por favor selecciona el titulo del resumen que quieres analizar");
        Analize.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        Parent.add(Analize, "card3");

        Search_Author.setBackground(new java.awt.Color(255, 255, 255));
        Search_Author.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Swis721 Cn BT", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Búsqueda por Autor");
        Search_Author.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxActionPerformed(evt);
            }
        });
        Search_Author.add(ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 130, -1));

        AutoresOrdenados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        AutoresOrdenados.setToolTipText("");
        jScrollPane3.setViewportView(AutoresOrdenados);

        Search_Author.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 510, 350));

        Buscar_Datos1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Buscar_Datos1.setText("BUSCAR");
        Buscar_Datos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar_Datos1ActionPerformed(evt);
            }
        });
        Search_Author.add(Buscar_Datos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 220, 40));

        Parent.add(Search_Author, "card4");

        Search_Key.setBackground(new java.awt.Color(255, 255, 255));
        Search_Key.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Swis721 Cn BT", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Búsqueda por palabra clave");
        Search_Key.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        Parent.add(Search_Key, "card5");

        Busqueda_Datos.setBackground(new java.awt.Color(255, 255, 255));
        Busqueda_Datos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Swis721 Cn BT", 1, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("DATOS DEL RESUMEN");
        Busqueda_Datos.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        datosResumen.setColumns(20);
        datosResumen.setRows(5);
        jScrollPane1.setViewportView(datosResumen);

        Busqueda_Datos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 88, 483, 384));

        Parent.add(Busqueda_Datos, "card6");

        getContentPane().add(Parent, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 610, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    private void LeerTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeerTXTActionPerformed
        Parent.removeAll();
        Parent.add(main);
        Parent.repaint();
        Parent.revalidate(); 
        Resumenes resumen=null;
        JFileChooser file = new JFileChooser();
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter(".TXT","txt");
        file.setFileSelectionMode(JFileChooser.FILES_ONLY);
        file.setFileFilter(filter);
        int selection=file.showOpenDialog(this);
        
        if(selection==JFileChooser.APPROVE_OPTION){
        
            File archive=file.getSelectedFile();
            String path=archive.getAbsolutePath();
        if(!path.contains("txt")) {
            JOptionPane.showMessageDialog(null, "Por favor elija un archivo del tipo txt");
            }
            else{
            try{
                File archivo = new File (path); 
                FileReader fr = new FileReader(archivo); 
                BufferedReader br = new BufferedReader(fr); 
                
                String Resumen;
                String ResumenInfo=""; 
      
        while ((Resumen=br.readLine())!=null) { 

            if(!Resumen.isEmpty()&& !Resumen.isBlank()) {
                ResumenInfo+=Resumen+"\n";
                

            }
        }
         fr.close();
        br.close();
        ResumenInfo=ResumenInfo.trim();

        if(!"".equals(ResumenInfo)) {
            HashTable hashtable=Global.getHashtable();
            List<Nodo<String>> listaTitulos= Global.getListaTitulos();

            String[] Info1=ResumenInfo.split("0_0");
            String[] Info2;
            String[] Info3;
            String[] Info4;
            String[] Info5;
            for (int i = 0; i < Info1.length; i++) {
                Info1[i]=Info1[i].trim();
                Info2=Info1[i].split("Autores");
               
            
                Info2[0]=Info2[0].trim();
                String titulo=Info2[0];
                Info2[1]=Info2[1].trim();
            
                 Info3=Info2[1].split("Resumen");
                Info3[0]=Info3[0].trim();
                String autores=Info3[0];
             Info4=Info3[1].trim().split("\n");
            String contenido=Info4[0];
            
             Info5=Info4[1].split(":");
            String keywords=Info5[1].trim();
            
            resumen=new Resumenes(titulo,autores,contenido,keywords);
            
            
            boolean repetido=hashtable.Insert(hashtable.Hash(resumen.getTitle()), resumen);
            
            if(repetido==false) {
                listaTitulos.insertFinal_String(resumen.getTitle());
                listaTitulos.Ordenar_Lista();
            
                JOptionPane.showMessageDialog(null, "Resumen cargado con exito");
                
                }

           
          }
            } 
            } catch(Exception e) {JOptionPane.showMessageDialog(null, "Error!!!"); }
            
            }
        }
    }//GEN-LAST:event_LeerTXTActionPerformed

    private void BuscarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarAutorActionPerformed
        Parent.removeAll();
        Parent.add(Search_Author);
        Parent.repaint();
        Parent.revalidate();

        ComboBox.removeAllItems();
        
        HashTable hashtable=Global.getHashtable();
        List<String> listaAutores = new List();
        for (int i = 0; i < hashtable.getTable().length ; i++){
            Nodo <Resumenes> aux = hashtable.getTable()[i].getFirst();
            while (aux!= null){
                String[] autores = aux.getData().getAuthors().split("\n");
                for(int j = 0; j < autores.length; j++){
                    listaAutores.insertFinal_String(autores[j]);
                }             
                aux = aux.getNext();
            }
        }
        
        
        for(Nodo<String> node = listaAutores.getFirst(); node != null; node = node.getNext()){
            ComboBox.addItem(node.getData());
        }

    }//GEN-LAST:event_BuscarAutorActionPerformed

    private void AnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalizarActionPerformed
        model.removeAllElements();
        Parent.removeAll();
        Parent.add(Analize);
        Parent.repaint();
        Parent.revalidate();
        List<Nodo<String>> listaTitulos= Global.getListaTitulos();
        Nodo<String> nodo = listaTitulos.getFirst();
        
        while (nodo!= null){
            model.addElement(nodo.getData());
            nodo = nodo.getNext();
        }
    }//GEN-LAST:event_AnalizarActionPerformed

    private void BuscarClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarClaveActionPerformed
        Parent.removeAll();
        Parent.add(Search_Key);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_BuscarClaveActionPerformed

    private void CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarActionPerformed
        HashTable hashtable=Global.getHashtable();
        String resumen="";
    for (int i = 0; i < hashtable.getTable().length ; i++){
        Nodo <Resumenes> aux = hashtable.getTable()[i].getFirst();
        
        while (aux!= null){
           resumen+= aux.getData().guardar()+"\n"+"0_0"+"\n"; // ---> lo de aqui es un objeto de clase resumen, si lo que quieres son su datos entonces tienes que ponerle tipo getTitle(), get...
            aux = aux.getNext();
        }
        
    }
            JOptionPane.showMessageDialog(null, "Escoja donde guardara los resumenes");
          JFileChooser file = new JFileChooser();
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter(".TXT","txt");
        file.setFileSelectionMode(JFileChooser.FILES_ONLY);
        file.setFileFilter(filter);
        int selection=file.showOpenDialog(null); //en la interfaz se pone this
        
        if(selection==JFileChooser.APPROVE_OPTION){
        
            File archive=file.getSelectedFile();
            String path=archive.getAbsolutePath();
        if(!path.contains("txt")) {
            JOptionPane.showMessageDialog(null, "Por favor elija un archivo del tipo txt");
            }
            else{
        try {
           PrintWriter pw=new PrintWriter(path); //para escribir, se pone la direccion de la carpeta\\nombre del archivo, si el archivo no existe lo crea
           
           pw.print(resumen);//mete todo de una en el txt borrando lo que habia anteriormente
           pw.close(); 
           JOptionPane.showMessageDialog(null, "Guardado exitoso");
       } catch(Exception e) {
           JOptionPane.showMessageDialog(null,"Error!!!");
       }
        
        }
    
    }
        System.exit(0);
    }//GEN-LAST:event_CerrarActionPerformed

    private void Buscar_DatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar_DatosActionPerformed

        String titulo = TitulosOrdenados.getSelectedValue();
        HashTable hashtable=Global.getHashtable();
        try{
            Nodo <Resumenes> nodo_seleccionado = hashtable.SearchTitle(hashtable.Hash(titulo),titulo);
            datosResumen.setText(nodo_seleccionado.getData().print());
            Parent.removeAll();
            Parent.add(Busqueda_Datos);
            Parent.repaint();
            Parent.revalidate();        
        }catch(Exception e ){
            JOptionPane.showMessageDialog(null, "Error!!!");
        }
    }//GEN-LAST:event_Buscar_DatosActionPerformed

    private void Buscar_Datos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar_Datos1ActionPerformed
        String titulo = AutoresOrdenados.getSelectedValue();
        HashTable hashtable=Global.getHashtable();
        try{
            Nodo <Resumenes> nodo_seleccionado = hashtable.SearchTitle(hashtable.Hash(titulo),titulo);
            datosResumen.setText(nodo_seleccionado.getData().print());
            Parent.removeAll();
            Parent.add(Busqueda_Datos);
            Parent.repaint();
            Parent.revalidate();        
        }catch(Exception e ){
            JOptionPane.showMessageDialog(null, "Error!!!");
        }
    }//GEN-LAST:event_Buscar_Datos1ActionPerformed

    private void ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxActionPerformed
        modelo.removeAllElements();
        if(ComboBox.getSelectedItem() != null){
           HashTable hashtable=Global.getHashtable();
            List<String> listaTitulos = new List();
            for (int i = 0; i < hashtable.getTable().length ; i++){
                Nodo <Resumenes> aux = hashtable.getTable()[i].getFirst();
                while (aux!= null && aux.getData().getAuthors().contains(ComboBox.getSelectedItem().toString())){
                listaTitulos.insertFinal_String(aux.getData().getTitle()); 
                aux = aux.getNext();
                }
            }
        
            for(Nodo<String> node = listaTitulos.getFirst(); node != null; node = node.getNext()){                
                modelo.addElement(node.getData());
            } 
        }        
    }//GEN-LAST:event_ComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Analizar;
    private javax.swing.JPanel Analize;
    private javax.swing.JList<String> AutoresOrdenados;
    private javax.swing.JButton BuscarAutor;
    private javax.swing.JButton BuscarClave;
    private javax.swing.JButton Buscar_Datos;
    private javax.swing.JButton Buscar_Datos1;
    private javax.swing.JPanel Busqueda_Datos;
    private javax.swing.JButton Cerrar;
    private javax.swing.JComboBox<String> ComboBox;
    private javax.swing.JButton LeerTXT;
    private javax.swing.JPanel Pannel;
    private javax.swing.JPanel Parent;
    private javax.swing.JPanel Search_Author;
    private javax.swing.JPanel Search_Key;
    private javax.swing.JList<String> TitulosOrdenados;
    private javax.swing.JTextArea datosResumen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel main;
    // End of variables declaration//GEN-END:variables
}
